version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=akram  # Make sure to set a strong password here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"  # Ensure PostgreSQL is exposed

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db  # Change 'localhost' to 'db' (Docker service name)
      - DJANGO_DB_NAME=library
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=akram
      - DJANGO_DB_PORT=5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
